### ISSUE TITLE
Update a Fact table

### ISSUE THREAD

**Issue by carlyk13** [chrthomsen/pygrametl#1]
Is there a way to do an upsert on a fact table? I'd like to update a record if it exists, otherwise, do an insert.

**Comment by chrthomsen** [comment]
No, there is no support for that at the moment. You can only insert and lookup fact rows.

I guess it would be relatively easy to add support for updates/upserts to FactTable. Do you have a good use case for updating facts?

**Comment by carlyk13** [comment]
It's not as common but certainly can happen in the accumulating snapshot
scenario.

The accumulating snapshot fact table corresponds to a predictable process
that has a well-defined beginning and end. Order processing, claims
processing, service call resolution and college admissions are typical
candidates. The grain of an accumulating snapshot for order processing, for
example, is usually the line item on the order. Notice in Figure 1 that
there are multiple dates representing the standard scenario that an order
undergoes. Accumulating snapshot records are revisited and overwritten as
the process progresses through its steps from beginning to end.
Accumulating snapshot fact tables generally are much smaller than the other
two types because of this overwriting strategy.

On Mon, Nov 9, 2015 at 6:33 AM, Christian Thomsen <notifications@github.com>
wrote:

> No, there is no support for that at the moment. You can only insert and
> lookup fact rows.
>
> I guess it would be relatively easy to add support for updates/upserts to
> FactTable. Do you have a good use case for updating facts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chrthomsen/pygrametl/issues/1#issuecomment-155063689>.
>



-- 
Carly Kaufman
*Data Services Product Manager*
[image: Inline image 1]

**Comment by chrthomsen** [comment]
Agreed, for accumulating snapshot fact tables it would make sense to support.updates.

I think the best way to support this would be to add a new class AccumulatingSnapshotFactTable (and a shorter alias). I don't think accumulating facts fit well with the existing FactTables. 

An instance of the new class should then know the FKs of the fact table, the subset of the FKs that identify a fact uniquely (when a fact is inserted, most dates would typically be unknown, but the rest of the FKs should still be unique), and the measures. Perhaps, it should also be optionally possible to have lag measures calculated automatically (similarly to what rowexpanders do for Dimensions).

I think this would be nice to add in a future release of pygrametl.

**Comment by HereticSK** [comment]
Timespan fact table may be another use case. According to The Data Warehouse Toolkit,
> 
> In more operational applications, you may want to retrieve the exact status of a customer at some arbitrary instant in the past. Was the customer on fraud alert when denied an extension of credit? How long had he been on fraud alert? How many times in the past two years has he been on fraud alert? How many customers were on fraud alert at some point in the past two years?
> 
> All these questions can be addressed if you carefully manage the transaction fact table containing all customer events. The key modeling step is to include a pair of date/time stamps. The first date/time stamp is the precise moment of the transaction, and the second date/time stamp is the exact moment of the next transaction. If this is done correctly, then the time history of customer transactions maintains an unbroken sequence of date/time stamps with no gaps. Each actual transaction enables you to associate both demographics and status with the customer.
> 
> The critical insight is that the pair of date/time stamps on a given transaction defines a span of time in which the demographics and the status are constant. Queries can take advantage of this “quiet” span of time. Thus if you want to know what the status of the customer “Jane Smith” was on July 18, 2013 at 6:33 am, you can issue the following query:

>     Select Customer.Customer_Name, Status
>     From Transaction_Fact, Customer_dim, Status_dim
>     Where Transaction_Fact_Customer_Key = Customer_dim.Customer_key
>     And Transaction_Fact.Status_key = Status_dim.Status_key
>     And Customer_dim.Customer_Name = 'Jane Smith'
>     And #July 18, 2013 6:33:00# >= Transaction_Fact.Begin_Eff_
>     DateTime
>     And #July 18, 2013 6:33:00# < Transaction_Fact.End_Eff_DateTime

**Comment by HereticSK** [comment]
Any plans to implement this?
