### ISSUE TITLE
Would it do a wrong update when using DimensionPartitioner with SlowlyChangingDimension on different physical tables?

### ISSUE THREAD

**Issue by HereticSK** [chrthomsen/pygrametl#10]
I've been reading the source code of `pygrametl` to get a deeper understanding (It is a great tool and I'm trying to use it in production environment).

According to the definition of `DimensionPartitioner.scdensure` in `pygrametl.tables.py`, line 2834-2837:
```Python
    def scdensure(self, row, namemapping={}):
        """Invoke scdensure on the relevant Dimension part"""
        part = self.getpart(row, namemapping)
        return part.scdensure(row, namemapping)
```
if I am not mistaken, **`DimensionPartitioner` only invokes `scdensure` once on one of its parts, and never check rows in other parts.** 

Consider this situation: 
There is a type 2 slowly changing dimension table in DW partitioned into 2 parts, say, `part A` and `part B`. And there are 2 versions of a member:
`row_in_A`: `|key0 | name | fromatt0 | toatt0|`, which lives in `part A`
`row_in_B`: `|key1 | name | toatt0 | maxto|`, which lives in `part B`

In this case, if I create an instance of `DimensionPartitioner`, `dp`, given `part A` and `part B` as its parts, and I get to proccess a row with the same version as `row_in_A`, when I invoke `dp.scdensure with this row`, **would there be a risk that dp finds it in `part A`, then it just do a `scdensure` within `part A`, but it should not do this since `row_in_B` is the newest version of the whole table.**

Am I understanding the code right? Is there a need to add some more defensive code to prevent that case? Or it is just a such terrible table design having 2 versions of a member live in 2 partitions, that we don't need to consider?

**Comment by chrthomsen** [comment]
Hello,

Thanks for your interest in pygrametl!

You are right that pygrametl only would look in one part and ignore any other parts for a given member. `DimensionPartitioner` uses the `lookupatts` of the parts to determine which part to operate on.

So if pygrametl is used from the beginning, the different versions of the member will be inserted into the same part by pygrametl. But if you have an existing DW where you have used another partitioning strategy inserting versions of a given member into different partitions, pygrametl cannot handle it. 

I think it would require bigger changes to support that case: A `BasePartitioner` would then not only be able to just delegate the work to another (single) instance. Instead it should operate on several instances. `SlowlyChangingDimension` would also need updates to support the case.

Best regards,
Christian Thomsen
