### ISSUE TITLE
Is there an attribute that dynamically obtains the size of _BatchFactTable__batch so that logging can be performed when inserting in different batches

### ISSUE THREAD

**Issue by qianxuanyon** [chrthomsen/pygrametl#23]
Hi

Is there an public attribute that dynamically obtains the size of _BatchFactTable__batch so that logging can be performed when inserting in different batches

Is there a more optimized way to replace the len operation in the following code
```python
process_rownum = 0
for row in resultsSource:
      tag_table.insert(row,namemapping=namemapping)
      if tag_table._BatchFactTable__batchsize == len(tag_table._BatchFactTable__batch)+1:
            process_rownum += tag_table._BatchFactTable__batchsize
            logger.info(f'Number of rows processed:{process_rownum}')
```

**Comment by chrthomsen** [comment]
Hi,

There is no public attribute for that. It would be nice to make that easily available. Thanks for the suggestion!

Best regards,
Christian
