### ISSUE TITLE
SnowflakedDimension.getbyvals() returns only one row

### ISSUE THREAD

**Issue by pepperblue** [chrthomsen/pygrametl#3]
Using given code in "Code Examples" and extending 'products-Data' (adding second entry "Calvin and Hobbes 1" with different price:

    {'name': 'Calvin and Hobbes 1', 'category': 'Comic', 'price': '10'},
    {'name': 'Calvin and Hobbes 1', 'category': 'Comic', 'price': '20'},

should return a list containing 2 rows with different values for "categoryid" when executing

    print(productDimension.getbyvals({'name': 'Calvin and Hobbes 1'}))

I think.

But only one row is returned ("categoryid" of returned row is "1").

When explicitly searching for row with "categoryid" being "2"

    print(productDimension.getbyvals({'name': 'Calvin and Hobbes 1', 'categoryid': '2'}))

the previous missing row is returned.

**Comment by chrthomsen** [comment]
Was this also solved with the new code that solved the problem in issue #4?

Thanks.

**Comment by pepperblue** [comment]
Yes, this issue is solved with code that solved the problem in issue #4.
I like solutions comming in quickly :smiley:
