### ISSUE TITLE
ConnectionWrapper.rowfactory() returns only the first row (Informix&pyodbc)

### ISSUE THREAD

**Issue by pepperblue** [chrthomsen/pygrametl#4]
Connecting to an Informix-DB using pyodbc as 'datasource' for ETL-Process things work as expected when I get data using SQLSource() (expected number of rows coming in). Trying to do the same using ConnectionWrapper.rowfactory() only one row is returned (the first one) and no more iterations take place.

**Comment by chrthomsen** [comment]
Hello,

Is this also the case with the newest code on GitHub? (We just fixed a problem where rowfactory only returned one row).

Best regards,
Christian Thomsen

**Comment by pepperblue** [comment]
ConnectionWrapper.rowfactory() is working fine using newest code on GitHub (bright smile and thumbs up)
