### ISSUE TITLE
JDBCConnectionWrapper: "rowfactory()" needs "resultnames()" as argument

### ISSUE THREAD

**Issue by pepperblue** [chrthomsen/pygrametl#5]
Connecting to Informix-DB as 'datasource' JDBCConnectionWrapper.rowfactory() returns a dict with incorrect keys (keys are only one single character) and at least one missing value. 'Solution' is passing JDBCConnectionWrapper.resultnames() as argument:

    data_source = informix_con_wrapper.rowfactory(names=informix_con_wrapper.resultnames())

In contrast ConnectionWrapper.rowfactory() 'behaves' identical with or without ConnectionWrapper.resultnames() as argument.

**Comment by chrthomsen** [comment]
Thanks for reporting this! I have committed a new version.
