### ISSUE TITLE
Issue on Dimension

### ISSUE THREAD

**Issue by leojosefm** [chrthomsen/pygrametl#7]
I'm getting below error for Dimension 
Code - 
```
productDimension = Dimension(
    name='product',
    key='productid',
    attributes=['name', 'category', 'price'],
    lookupatts=['name'])
```

Error -

> Traceback (most recent call last):
>   File "petl_demo.py", line 19, in <module>
>     lookupatts=['name'])
>   File "C:\Anaconda3\lib\site-packages\pygrametl\tables.py", line 189, in __init__
>     (self.quote(key), name))
>   File "C:\Anaconda3\lib\site-packages\pygrametl\__init__.py", line 663, in execute
>     self.__cursor.execute(stmt, arguments)
> TypeError: expecting a dictionary, sequence or keyword args

**Comment by chrthomsen** [comment]
Hello,

I cannot recreate that error. Do you get the error when you create the Dimension instance or when you use it (e.g., with insert(...) or ensure(...))? And which DB driver do you use?

Best regards,
Christian Thomsen

**Comment by leojosefm** [comment]
Hi,

I'm getting that error when I create dimension instance. I'm connecting to oracle DB

```
conn_str=u'hr/hr@localhost:1521/PDBORCL'
conn= cx.connect(conn_str)
dw_conn=pygrametl.ConnectionWrapper(connection=conn)
```

I'm able to create fact table instance using below code  -

```
factTable = FactTable(
    name='facttable',
    measures=['price'],
    keyrefs=['storeid', 'productid', 'dateid'])

```

**Comment by chrthomsen** [comment]
Hi,

Could you please try again with the new __init__.py that I just committed? I hope that solves the problem.

Best regards,
Christian Thomsen

**Comment by leojosefm** [comment]
Hi,

Thank you so much Christian. It worked!! . I'm actually new to Python,
without much experience to programming apart from some shell scripting.

Please can you let me know the fix?



On Thu, Oct 27, 2016 at 8:42 AM, Christian Thomsen <notifications@github.com

**Comment by chrthomsen** [comment]
Hi,

Good that it works. You can see the changes here: https://github.com/chrthomsen/pygrametl/commit/dd76903a6f49e35d7d8d1747bf0b2d5fe2beb99a In short, we sometimes passed a None value to the underlying cursor's execute method. Some PEP249 implementations accept that, others don't, so now we don't pass the None value anymore to be safe.

Best regards,
Christian

P.S. You reported this for the Dimension class. Note that CachedDimension often will lead to much better performance.
