### ISSUE TITLE
Beginner Sample CSVSource takes at lease 2 arguments

### ISSUE THREAD

**Issue by Freewilly3d** [chrthomsen/pygrametl#8]
I'm trying to run the beginner sample and I'm getting an error on the CSVSource

    region_file_handle = open('region.csv','r',16384)
    region_source = CSVSource(csvfile=region_file_handle,delimiter=',')

    region_source = CSVSource(csvfile=region_file_handle,delimiter=',')
    TypeError: __init__() takes at least 2 arguments (1 given)

Process finished with exit code 1

Python 2.7.11 64 bit

**Comment by xcalibur666** [comment]
According to https://chrthomsen.github.io/pygrametl/doc/api/datasources.html you also need a casts :)

`class pygrametl.datasources.TypedCSVSource(csvfile, casts, fieldnames=None, restkey=None, restval=None, dialect='excel', *args, **kwds)`

**Comment by xcalibur666** [comment]
Sorry, ignore my previous comment, you are not using TypedCSVSource but CSVSource.

CSVSource is just using pythons DictReader, and the documentation of DictReader says:
`class csv.DictReader(csvfile, fieldnames=None, restkey=None, restval=None, dialect='excel', *args, **kwds)`
https://docs.python.org/2.7/library/csv.html#csv.DictReader

But when running
`from pygrametl.datasources import CSVSource`
`help(CSVSource)`
the help tells (shortened):
`Help on class DictReader in module csv:`
`__init__(self, f, fieldnames=None, restkey=None, restval=None, dialect='excel', *args, **kwds)`

So actually you should call CSVSource like
`region_file_handle = open('region.csv','r',16384)`
`region_source = CSVSource(f=region_file_handle,delimiter=',')`

So I understand your fuzziness over the error, but the parameter to CSVSource is not **csvfile** but **f**.

**Comment by Freewilly3d** [comment]
Are the groups monitored?  I have a couple other questions...
1) when I tried to debug the error above in pycharm the "step into" didn't
2) I'm using portable posgres on windows I found I had to change the syntax of the fact and dimensions to something like this:
    location_dimension = Dimension(
        name='public."Location"',
        key='"LocationID"',
        attributes=['"City"', '"Region"'],
        lookupatts=['"City"'])
3) Related to #2 [location_dimension.insert(row) for row in region_source]  is failing 
[Pygrametl_beginner_example-py.txt](https://github.com/chrthomsen/pygrametl/files/571722/Pygrametl_beginner_example-py.txt)
[Beginner_example_ddl for dw_sql.txt](https://github.com/chrthomsen/pygrametl/files/571723/Beginner_example_ddl.for.dw_sql.txt)

with a KeyError: '"City"'
